### ISSUE TITLE
Consuming events within ASP.NET Core services

### ISSUE THREAD

**Issue by WhitWaldo** [loekd/ServiceFabric.PubSubActors#106]
Your sample solution has an ASP.NET API producing events for the other services to consume. This works great, but how might I subscribe to listen to the events within a controller?

Your subscriber base and alternative registration approaches seem to require setup on the service entry and while that sets up the IBrokerClient to publish services, it's not clear how I might subscribe to the services within the controllers (or on a page).

I tried to set this up to use more of the ASP.NET Core DI approach with the following:

```
public static class SubscriberAspNetExtensions
    {
        public static IServiceCollection AddPubSubSubscriptions(this IServiceCollection services,
            string applicationName, Uri serviceUri, ServicePartitionKind partitionKind)
        {
            var reference = new ServiceReference
            {
                ApplicationName = applicationName,
                ServiceUri = serviceUri,
                PartitionKind = partitionKind
            };

            return AddPubSubSubscriptions(services, reference);
        }

        public static IServiceCollection AddPubSubSubscriptions(this IServiceCollection services, ServiceReference serviceReference)
        {
            if (services == null)
                throw new ArgumentNullException(nameof(services));

            var brokerClient = new BrokerClient();

            var tasks = new List<Task>();

            foreach (var subscription in DiscoverHandlers())
            {
                var subscribeAttribute = subscription.Value;

                try
                {
                    var subscribeTask = brokerClient.SubscribeAsync(new ServiceReferenceWrapper(serviceReference),
                        subscription.Key, subscribeAttribute.Handler,
                        subscribeAttribute.QueueType == QueueType.Ordered);
                    tasks.Add(subscribeTask);
                    ServiceEventSource.Current.Message($"Registered service: '{serviceReference.ServiceUri}' as subscriber of '{subscription.Key}'");
                }
                catch (Exception ex)
                {
                    ServiceEventSource.Current.Message($"Failed to register service '{serviceReference.ServiceUri}' as a subscriber of '{subscription.Key}'. Error: '{ex.Message}'");
                    throw;
                }
            }

            //Actually perform the registrations
            Task.WaitAll(tasks.ToArray());

            //And set up the broker client
            services.AddSingleton<IBrokerClient>(brokerClient);

            return services;
        }

        /// <summary>
        /// Finds each of the methods decorated with the <see cref="SubscribeAttribute"/> attribute.
        /// </summary>
        /// <returns></returns>
        private static Dictionary<Type, SubscribeAttribute> DiscoverHandlers()
        {
            var subscribeAttributes = new Dictionary<Type, SubscribeAttribute>();
            var taskType = typeof(Task);

            //Get each of the methods in this app domain that are decorated with the Subscribe attribute

            var targetTypes = Assembly.GetExecutingAssembly()
                .GetTypes();

            foreach (var type in targetTypes)
            {
                var methods = type.GetMethods(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                    .Where(method => method.GetCustomAttributes(typeof(SubscribeAttribute), false).Length > 0)
                    .ToList();

                if (!methods.Any())
                    continue;

                //Iterate through each to identify the attributes and pull their values for the dictionary
                foreach (var method in methods)
                {
                    var subAttribute = method.GetCustomAttributes(typeof(SubscribeAttribute), false)
                        .Cast<SubscribeAttribute>()
                        .SingleOrDefault();

                    if (subAttribute == null)
                        continue;

                    var parameters = method.GetParameters();
                    if (parameters.Length != 1 || !taskType.IsAssignableFrom(method.ReturnType))
                        continue;

                    subAttribute.Handler = m => (Task) method.Invoke(type, new[] {m});
                    subscribeAttributes[parameters[0].ParameterType] = subAttribute;
                }
            }
            
            return subscribeAttributes;
        }
    }
```

The idea being here that all the methods in the assembly with [Subscribe] are pre-registered. No need for base classes or your other means of registering and instead just add `services.AddPubSubSubscriptions()` and pass in the name of the app, the URI to the service and the partition kind.

Unfortunately, that doesn't work either (and I'm still trying to dig into why).

Do you have any ideas of how I might go about subscribing to services within an ASP.NET Core service (such that I might see the events in something like a page)?

Thank you!

**Comment by danadesrosiers** [comment]
Service Fabric Pub/Sub is built on [Service Fabric Remoting](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting).  This means that the broker is sending messages directly to the Service Fabric Stateful Service, Stateless Service, or Actor.  There are good reasons we created base classes, believe me, I wish there was a cleaner way.

The methods `StatelessService.CreateServiceInstanceListeners()` and `StatefulService.CreateServiceReplicaListeners()` set up the listener so the Service can accept messages.

The method `ReceiveMessageAsync()` on the base classes are required because this is the method that the broker calls with messages.  It is the method that actually accepts messages.

The base classes subscribe to messages in `StatelessService.OnOpenAsync()` and `StatefulService.OnOpenAsync()` because this is a life cycle hook where we know that the service is ready to begin interacting with the broker.  If you try to subscribe before this time, it won't work.

Your ASP.NET Core service is probably a `StatelessService` which sets up a `KestrelCommunicationListener`.  In order to subscribe to messages in this service, you would need to set up a second listener for Service Fabric Remoting similar to how it is done in the base class.

Then implement the `ReceiveMessageAsync()` method just like the base class.

Also implement the `OnOpenAsync()` method to subscribe to messages.  Here you could use your global `DiscoverHandlers()` method to find all `Subscribe` attributes instead of the built in extension method that only looks in the Service.

The `ReceiveMessageAsync()` method receives all messages and calls the handler.  There is no reason the handler can't be anywhere, though it would have to be a static method.

I'm still not sure how you could consume it from a page.  I suppose maybe if it's a Server Side Blazor component.  I hope this helps either solve your problem or understand why it is not possible, if that is the case.

**Comment by WhitWaldo** [comment]
I've created a few different POCs trying to consume this from the page, but so far the difficulty lies in the fact that all the remoting happens at the service level, all the registration for the web happens only at initialization and because there's no exposure from the web app container to the service, there's no way to access any of the DI components to communicate from the service to the app after the fact.

I've opened a ticket with the Service Fabric team to see if I can't get any ideas from them of how to proceed and will write back should they provide any.

Thank you for responding!

**Comment by WhitWaldo** [comment]
I ultimately figured out how to go about doing this. Sharing my notes here for any future visitors curious about the same. I've got a public GitHub repo up at [https://github.com/WhitWaldo/sf-pubsub-test/tree/simple](https://github.com/WhitWaldo/sf-pubsub-test/tree/simple) that demonstrates the idea.

Within the Blazor directory, I created a class called [MessageHost ](https://github.com/WhitWaldo/sf-pubsub-test/blob/simple/Blazor/MessageHost.cs) that largely just fires off an event whenever a message is added to it.

In my Blazor.cs class, I set it up to implement the [SubscriberStatelessServiceBase](https://github.com/WhitWaldo/sf-pubsub-test/blob/f335af58a6732bcbb8f874daeeb40d10758991dc/Blazor/Blazor.cs#L19) from this project and create a new private [instance](https://github.com/WhitWaldo/sf-pubsub-test/blob/f335af58a6732bcbb8f874daeeb40d10758991dc/Blazor/Blazor.cs#L21) of the MessageHost. When a message is received, I add it to this MessageHost. Within the WebHostBuilder, I then add this MessageHost instance as a [singleton](https://github.com/WhitWaldo/sf-pubsub-test/blob/f335af58a6732bcbb8f874daeeb40d10758991dc/Blazor/Blazor.cs#L62). 

In my [Blazor](https://github.com/WhitWaldo/sf-pubsub-test/blob/simple/Blazor/Pages/Home.razor) page then, I inject the MessageHost instance and as part of the OnInitialized override, I subscribe to the event on this instance indicating a message has changed. As part of that callback, I update the local Messages state to reflect the current Messages contents on the MessageHost. Note that I'll unsubscribe from the event in the Dispose method.

And with that, one can now use SoCreate's PubSub service within a Blazor app to push messages from other services into the website for display (instead of always calling out to pull the same).
