### ISSUE TITLE
The provided URI scheme 'http' is invalid; expected 'net.tcp'

### ISSUE THREAD

**Issue by MonDeveloper** [loekd/ServiceFabric.PubSubActors#33]
Subscriber so not receive any messages.
BrokerService always fails with this exception:

> System.ArgumentException occurred
  HResult=0x80070057
  Message=The provided URI scheme 'http' is invalid; expected 'net.tcp'.
Parameter name: via
  Source=System.ServiceModel
  StackTrace:
   at System.ServiceModel.Channels.TransportChannelFactory`1.ValidateScheme(Uri via)

The code responsible is in the class 
``` c#
internal class SubscriberServicePartitionClient : ServicePartitionClient<WcfCommunicationClient<ISubscriberService>>, ISubscriberService
```
and the method is: 
``` c#
		public Task ReceiveMessageAsync(MessageWrapper message)
		{
			return InvokeWithRetryAsync(
			   client => client.Channel.ReceiveMessageAsync(message));
		}
```

Could you please help me understanding if the problem is at "client side"  (I mean the Broker) or the "server side" (i mean the Subscriber) ?

**Comment by loekd** [comment]
Do you expose multiple communication listeners in the subscriber service?
If so, the pubsub one must be the default one.

Sent from Nine<http://www.9folders.com/>
________________________________
Van: Marco Monducci <notifications@github.com>
verzonden: 17 nov. 2017 2:02 p.m.
Aan: loekd/ServiceFabric.PubSubActors
Cc: Subscribed
Onderwerp: [loekd/ServiceFabric.PubSubActors] The provided URI scheme 'http' is invalid; expected 'net.tcp' (#33)


Subscriber so not receive any messages.
BrokerService always fails with this exception:

System.ArgumentException occurred
HResult=0x80070057
Message=The provided URI scheme 'http' is invalid; expected 'net.tcp'.
Parameter name: via
Source=System.ServiceModel
StackTrace:
at System.ServiceModel.Channels.TransportChannelFactory`1.ValidateScheme(Uri via)

The code responsible is in the class

internal class SubscriberServicePartitionClient : ServicePartitionClient<WcfCommunicationClient<ISubscriberService>>, ISubscriberService

and the method is:

                public Task ReceiveMessageAsync(MessageWrapper message)
                {
                        return InvokeWithRetryAsync(
                           client => client.Channel.ReceiveMessageAsync(message));
                }

Could you please help me understanding if the problem is at "client side" (I mean the Broker) or the "server side" (i mean the Subscriber) ?

**Comment by MonDeveloper** [comment]
Yes, I DO (i'm sorry)
How to declare the default one?

**Comment by loekd** [comment]
Make sure to return '
SubscriberCommunicationListener' first.

Sent from Nine<http://www.9folders.com/>
________________________________
Van: Marco Monducci <notifications@github.com>
verzonden: 17 nov. 2017 8:52 p.m.
Aan: loekd/ServiceFabric.PubSubActors
Cc: loekd; Comment
Onderwerp: Re: [loekd/ServiceFabric.PubSubActors] The provided URI scheme 'http' is invalid; expected 'net.tcp' (#33)


Yes, I DO (i'm sorry)
How to declare the default one?

**Comment by MonDeveloper** [comment]
Moving the `SubscriberCommunicationListener` as first listener didn't work but leaving it alone does.
My intention was to use a Stateless WebAPI as subscriber so I need to work on it but I can try by myself, your suggestion drive me in the right direction, thank you!

Anyway, I can't stop boring you, I have another question, why did you choose WCF over plain Remoting for the subscriber message delivery?

**Comment by loekd** [comment]
The latest version no longer uses WCF.
