### ISSUE TITLE
Why PubSubActor over direct actor to actor/service communication

### ISSUE THREAD

**Issue by prapicault** [loekd/ServiceFabric.PubSubActors#34]
Hi, 
I'm looking at this library and I'm trying to understand which problem of actor-to-actor communication it helps solve. Could you please explain what is wrong with the actor-to-actor approach and how this library improves the situation especially on the reliability front.
Thanks,

**Comment by guibirow** [comment]
An Actor-to-Actor approach is 1-to-1 communication. The PubSub proposed here is 1-to-many.
Search about the Publish\Subscribe pattern that you will understand better.

**Comment by loekd** [comment]
If you are in a situation where 10 Actors need to be updated if 1 Actor (X) changes.

- you can call all 10 Actors from X, one by one. The processing time will be slow, if one Actor fails, the entire operation fails. Timeouts are to be expected.

- alternatively, you can broadcast the change and let the 10 subscribers deal with the change in their own time and pace. The processing time will be fast (call just the broker) and reliable (because of built-in retry support per subscriber)

_Note_: You can replace `Actor` with `Service` in the story above, or mix and match.

**Comment by prapicault** [comment]
Thanks @loekd I'll play with this.
