### ISSUE TITLE
PubSubActors and V2Remoting

### ISSUE THREAD

**Issue by mitkodev** [loekd/ServiceFabric.PubSubActors#37]
Hey,

I just wanted to leave a comment since I've spent the day struggling to setup the most basic setup, just like in the demo and the problem was that with the latest Service Fabric version 6.1.472, the Actors created in visual studio are created with support for V2 remoting, which caused this error:
```
Element 'http://schemas.microsoft.com/2003/10/Serialization/:anyType' 
contains data from a type that maps to the name 'urn:ServiceFabric.Communication:ServiceResponseMessageHeaders'. 
The deserializer has no knowledge of any type that maps to this name. 
Consider using a DataContractResolver if you are using DataContractSerializer or add the 
type corresponding to 'ServiceResponseMessageHeaders' 
to the list of known types - for example, by using the
 KnownTypeAttribute attribute or by adding it to the list of known types passed to the serializer.
```

This is a known issue, if you check the SF issues, but I was not sure if this was supported so I manually reverted the actors to V1.

The next possible issue is that the default template for an actor comes with overriden OnActivate method without calling the base method, which is breaking the initialization of the __state__ for the Broker Actor (took some time to spot such simple mistake :D )

And the last thing as far as i seen - PublisherServiceExtensions use the Stateless/Stateful service, just to get application name from the context, but in an aspnet core service, it is easier to inject the context itself and have access to it everywhere in the code.

Those are just my observations, however thanks for the repo, looks like we're going to use it extensively 👍

**Comment by loekd** [comment]
Thanks for your feedback!

**Comment by danadesrosiers** [comment]
Thanks again for sharing your experiences!  A lot has happened since this issue was created.  I think the issues you experienced have been resolved at this point.  The V2 remoting issues have been solved in recent SF versions.  BrokerActor and PublisherServiceExtensions no longer exist.  And the package now uses remoting V2 exclusively.  

I'm closing this issue since it is enough out of date that it probably isn't helpful anymore.  Please create another if you have any more issues.
