### ISSUE TITLE
Broker publish - v2 Remoting

### ISSUE THREAD

**Issue by koderi-dp** [loekd/ServiceFabric.PubSubActors#53]
Hi,

I think this could be issue if broker, subscriber is set to use v2 remoting or services are net core

MessageWrapperExtensions

 private static readonly Lazy<IServiceProxyFactory> ServiceProxyFactoryLazy = new Lazy<IServiceProxyFactory>(()=> new ServiceProxyFactory());

and this function could thow error, something like this

"RunAsync - Exception caught while processing messages:'NamedEndpoint 'V2_1Listener' not found in the address

Task PublishAsync(this ServiceReferenceWrapper wrapper, MessageWrapper message)

i think it is used to send message to subscriber?

subscriber should somehow define which remoting it is using?

**Comment by loekd** [comment]
Doesn't this depend on how you configure [service remoting](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#upgrade-from-remoting-v1-to-remoting-v2) on the subscriber side?

**Comment by danadesrosiers** [comment]
I recently encountered this issue as well.  I think this what happened:

The original V2 Remoting work let the user decide (through a configuration) to set up listeners on the Broker using V2.  The BrokerLocatorService, which the publisher uses to create the ServiceProxy to publish messages to the Broker, did not have such a configuration.  I added this when I updated to SF 3.3.624 in the 7.4.1 release of this package.

Now a publisher can send messages to the Broker using V2, but the Broker is still sending messages to subscribers using V1 because the ServiceProxyFactory is created in the V1 way in MessageWrapperExtensions.  I got the same error as you when I set up a Stateful Subscriber Service listening on V2.

There are 2 possible solutions:
1. Use the assembly directive in your derived Broker Service to specify the remoting version.
2. Refactor to create the ServiceProxyFactory properly based on the `useRemotingV2` config.

I got option 2 working, but I am starting to favor option 1 more and more.  This lets the user control the remoting version on their end.  Then we can use generic methods in the library instead of managing all possible options.  What do you think, @loekd?

**Comment by loekd** [comment]
I'm inclined towards using option 1, there already are 3 versions of remoting out there.

**Comment by koderi-dp** [comment]
Then option 1, this should be defined like note in documentation
