### ISSUE TITLE
Support Both Ordered and Unordered in BrokerService

### ISSUE THREAD

**Issue by danadesrosiers** [loekd/ServiceFabric.PubSubActors#58]
Currently, if you need some message types to be delivered in order, and others need the high throughput that unordered processing provides, you need to run two separate Broker Services.  You would also not be able to use automatic BrokerService location.  It would be nice if one Broker Service could handle both.  The subscriber would specify ordered or unordered when subscribing.

Another possible solution would be to have 2 Broker services, but give the BrokerServiceUnordered a different name so the BrokerServiceLocator could find the right one based on the message type.

**Comment by loekd** [comment]
I'm trying to image what the consequences would be on the performance /throughput. Need to reflect on this a bit, if that's ok.

**Comment by danadesrosiers** [comment]
I'm not in a hurry on this one.  It's mostly an idea I wanted to put out there.  I think there are ways to improve how the Broker processes queues that would increase throughput and make it possible to handle ordered and unordered in one service without compromising performance.  I don't have all the answers yet, but I'm guessing that they include such buzzwords as "reactive" and/or "async streams".

**Comment by koderi-dp** [comment]
this is good idea, i did have some issues if i wanted to use default broker or unordered broker based on configuration, but it is not possible with current implementation, had some general idea to move most of stuff from broker service into some kind of store, and to have only one broker service, and different store implementations, i'm not yet satisfied with this, there should be way do remove abstract implementation, and have only one, and maybe have queue type abstracted, it's only abstract because of queue creation... maybe to create queue wrapper with default required actions. dequeue, enqueue etc...

i have also added possibility to define store broker state key, in theory it could be possible to host multiple stores with different keys.. i think, not sure... :)

https://github.com/danijel-peric/ServiceFabric.PubSubActors/tree/master/ServiceFabric.PubSubActors/Store

and some quick example to create mock up store

https://github.com/danijel-peric/ServiceFabric.PubSubActors/blob/master/ServiceFabric.PubSubActors.Tests/InMemoryBrokerStore.cs

**Comment by loekd** [comment]
@danadesrosiers : in theory, performance could be limited by network bandwidth. If you have lots of messages and not many message types, you could well run out. Having 2 brokers would allow using 2 machines, doubling bandwidth. So we need to make sure we offer options to end users to select their desired setup.
@danijel-peric  I would like it if we can compose a broker service instead of the current rigid setup. And you're right, for some scenarios you might not need persistence inside the broker.

**Comment by danadesrosiers** [comment]
@danijel-peric, I think you're on the right track.

@loekd, I don't follow.  We currently load balance message types over partitions, but, you're right, one message type could put a high load on one partition.  I don't see how having two brokers helps that since a single message type still goes to one partition on a single broker.  We could potentially increase bandwidth by having the BrokerLocatorService load balance across multiple partitions for a single message type.

As far as bottleneck concerns, first on my list is the polling nature of message delivery.  The BrokerService runs on a polling loop, looking for new messages to send for each queue.  Each queue is processed in parallel using `Task.WhenAll`, but all queues need to finish before the current iteration is completed and the next can begin.  A slower ordered queue could potentially slow down a faster unordered queue in this way.  That's my greatest concern with merging the two types.  There's also a delay between iterations.  I'm not sure exactly what it would look like yet, but we probably want a more reactive process.

**Comment by radderz** [comment]
One options that would work for some designs would be a partition key for a message type, so that if a type is used by many objects, but has a way to partition them in some way, then you could have ordered partitions by using multiple reliable queues for specific type.

I.e. if messageTypeA for objectA needs to be in order just for objectA, then messageTypeB for objectB could be a separate queue.

This would suit our needs more as we have many devices that need to be processed in a FIFO basis and we tend to use multiple queues where the same device would always be in the same queue (resulting in per object FIFO). This could be dealt with by using subclasses of the message type I suppose but its not ideal to have a hundred clones of the same message type for this purpose.

**Comment by danadesrosiers** [comment]
Thanks for the suggestion, @radderz!  I've actually been thinking about a similar feature.  I was thinking of calling it something like "ordering facet".  It would be an optimization of an ordered queued, not an unordered queue, so it would be a different feature than the one proposed in this issue.  

A queue that does not require strict ordering can use an IReliableConcurrentQueue, which is significantly faster than an IReliableQueue, which guarantees ordering.  When ordering is required, we must use an IReliableQueue, but then we can introduce optimizations such as the one you suggest to improve the performance.
