### ISSUE TITLE
Optional Parameter in BrokerService Interface

### ISSUE THREAD

**Issue by BoeseB** [loekd/ServiceFabric.PubSubActors#61]
I can't get a simple example to work. The broker service can't get instatiated and fails with the following error message.

> Method 'RegisterSubscriberAsync' of service interface 'ServiceFabric.PubSubActors.IBrokerService' has out/ref/optional parameter 'routingKey'. The service interface methods must not have out, ref or optional parameter

Am i doing something wrong or is this a bug?

ServiceFabric SDK Version: 3.3.638

BrokerServiceCode:
```
    internal sealed class PubSubBrokerService : BrokerService
    {
        public PubSubBrokerService(StatefulServiceContext context)
            : base(context, true, true)
        {
            ServiceEventSourceMessageCallback = message => ServiceEventSource.Current.ServiceMessage(context, message);
        }
    }
```
AppManifest:
```
...
    <Endpoints>
      <Endpoint Name="ServiceEndpointV2" />
      <Endpoint Name="ReplicatorEndpoint" />
    </Endpoints>
....
```

**Comment by loekd** [comment]
Thanks for your feedback. Sorry about that. That is a bug indeed.
Can you please try v7.6.2?

**Comment by BoeseB** [comment]
No need to appologize, good work so far and thanks for the quick fix. 

Works with v7.6.2

Do you by chance have some links to the pattern this library implements related to microservices? I am new to this and would love to understand the inner workings a bit better.

**Comment by loekd** [comment]
Sure, it works by using the [pub/sub pattern](https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern). This allows you to decouple the sender and receiver(s) of information. Instead of performing a direct call to the receiver, you delegate that work to a broker. The broker will make a persisted copy of the message for every subscriber and send them the message asap. Aside from fewer run-time dependencies, this pattern allows for outages in receivers.
More links:
[MSDN](https://docs.microsoft.com/en-us/azure/architecture/patterns/publisher-subscriber)
[Fowler](https://martinfowler.com/eaaDev/EventCollaboration.html)
