### ISSUE TITLE
NullReference Exception on Subscribe

### ISSUE THREAD

**Issue by BoeseB** [loekd/ServiceFabric.PubSubActors#71]
Every other start of my service fabric application i get errors on subscribing to messages via the broker.
The subscription is made from the OnOpenAsync method, ad the brokerClient initialized in the constructor.

Is there any issue with the following code or is this maybe a bug in the PubSub implementation?
I also sometimes had a concurrency exception which was also thrown in OnSubscribedAsync Of the DefaultBrokerEventsManager.

### Code
```
        protected override async Task OnOpenAsync(ReplicaOpenMode openMode, CancellationToken cancellationToken)
        {
            await _brokerClient.SubscribeAsync<CamAdded>(this, Handle);
        }
```

```
    internal sealed class CamDeviceSvc: StatefulService, ICamDeviceSvc
    {
        private IBrokerClient _brokerClient;

        public XovisDeviceSvc(StatefulServiceContext context)
            : base(context)
        {
            _brokerClient = new BrokerClient();
        }
```

 `    public interface IXovisDeviceSvc : ISubscriberService`

### Stacktrace
![image](https://user-images.githubusercontent.com/13516762/58400896-ab40ad80-805c-11e9-9205-553f4fcb5a31.png)

**Comment by danadesrosiers** [comment]
I assume `ICamDeviceSvc` extends `ISubscriberService` (you mentioned `IXovisDeviceSvc`).

I assume also that you have implemented `ReceiveMessageAsync` and `CreateServiceInstanceListeners` as mentioned in the documentation.  Since you are not using the Base class, you have to implement this boilerplate yourself.  If it's not exactly right, messages won't be delivered.  The base class also has some retry logic that might be helpful.

I assume that `Handle` has also been implemented.

With these assumptions, everything looks correct.

From the stack trace, it seems to be blowing up in `DefaultBrokerEventsManager.OnSubscribeAsync()` when it tries to add a new element to the `_stats` dictionary.  I was able to reproduce the exception in a unit test by setting the ReferenceWrapper to null, but I don't know how this could happen.

Can you provide more details on how to reproduce the error?  Maybe set up a temporary Github project I could clone and play with myself.  How are you starting the Application?  Just "Deploy Solution" in Visual Studio?

**Comment by loekd** [comment]
@danadesrosiers  A null reference exception on a dictionary is usually caused by concurrent write access to the dictionary.
This is further supported by TS remark about a `ConcurrencyException`.

So I think the `_stats` object should probably be a `ConcurrentDictionary`.

https://github.com/SoCreate/service-fabric-pub-sub/pull/73

**Comment by BoeseB** [comment]
Hi, thanks for the replies.

@danadesrosiers Your assumptions are correct. And i start the app out of VS just by starting the SF App with F5 in Debug mode. 
@loekd That would explain why sometimes its a concurrency exception and sometimes its the null when both can be concurrency issues.

I could not find where the problems originate from because there is no further interaction on Startup with the broker client than the subscribe call from my code.

**Comment by danadesrosiers** [comment]
v9.1.1 is now available.  Please let us know if you continue to experience errors.
